# Generated by Django 3.2 on 2021-04-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
