# Generated by Django 3.2 on 2021-04-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
