# Generated by Django 3.2 on 2021-04-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='000-000-000-000-0', max_length=17, unique=True),
        ),
    ]
