# Generated by Django 3.2 on 2021-04-20 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0011_alter_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_period', models.DateField()),
                ('book_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
