# Generated by Django 3.2 on 2021-04-20 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_detail',
            old_name='request_period',
            new_name='return_date',
        ),
    ]
