# Generated by Django 3.2 on 2021-04-20 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0002_rename_request_period_request_detail_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_detail',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 12, 43, 58, 672014, tzinfo=utc)),
        ),
    ]
