# Generated by Django 3.2 on 2021-04-21 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0003_alter_request_detail_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_detail',
            name='request_status',
            field=models.CharField(default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='request_detail',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 28, 6, 56, 7, 75866, tzinfo=utc)),
        ),
    ]
