# Generated by Django 3.2 on 2021-04-21 08:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0005_alter_request_detail_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_detail',
            name='confirm_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request_detail',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 28, 8, 41, 55, 670961, tzinfo=utc)),
        ),
    ]
